import pandas as pd

def prepareData(tableau):
    customIndex = {
        'Fiche ' : "fiche",
        'Juridiction' : "juridiction",
        'code NATINF des atteintes à la probité' : "codeNATINF",
        ' codes NATINF - infraction connexe d\'atteintes à la probité  ' : "codeNATINFconnexe",
        'infraction' : "infraction",
        'personne physique /personne morale' : "personne",
        'sexe' : "sexe",
        'année de naissance' : "anneeNaissance",
        'âge au moment des faits' : "ageMomentFaits",
        'qualité des prévenus ' : "qualitePrevenus",
        'secteur économique public concerné ' : "secteurPublic",
        'secteur économique privé concerné ' : "secteurPrive",
        'Profession et catégorie socioprofessionnelle' : "ProfessionEtCategorie",
        'mode opératoire I (description littérale)' : "descriptionModeOperatoire",
        'montant des enjeux financiers ' : "montantEnjeux",
        'département du lieu de commission des faits' : "departementCommissionFaits",
        'région du lieu de commissions des faits' : "regionCommissionFaits",
        'début de la période de prévention' : "debutPrevention",
        'Année de début de prévention' : "anneeDebutPrevention",
        'fin de la période de prévention' : "finPrevention",
        'durée de la période de prévention\n(en nbr jours)' : "dureePrevention",
        'origine de l’affaire' : "origineAffaire",
        'service judiciaire saisi' : "serviceJudiciaireSaisi",
        'mode de poursuite retenu ' : "modePoursuiteRetenu",
        'parties civiles -personne physique \nNombre' : "nbrPartiesCivilesPhysiques",
        'parties civiles - personne morale\nNombre' : "nbrPartiesCivilesMorales",
        'parties civiles - personne morale 1' : "PartieCivileMorale1",
        'parties civiles - personne morale 2' : "PartieCivileMorale2",
        'parties civiles - personne morale 3' : "PartieCivileMorale3",
        'Date de l\'audience ' : "dateAudience",
        'Date du jugement ' : "dateJugement",
        'nullité soulevée ' : "nulliteSoulevee",
        'sens de la décision par prevenu ' : "sensDecision",
        'peines par prevenu' : "peines",
        'durée de l\'emprisonnement (mois) ' : "dureeEmprisonnement",
        'Mandat de dépôt' : "mandatDepot",
        'sursis' : "sursis",
        'durée du sursis\n(mois)' : "dureeSursis",
        'montant de l\'amende' : "montantAmende",
        'sursis sur amende' : "sursisAmende",
        'jour amende' : "jourAmende",
        'peines complémentaires  ' : "peinesComplementaires",
        'interdiction d\'exercice de toute fonction ou emploi public' : "interdictionEmploiPublic",
        'durée' : "dureeInterdictionEmploiPublic",
        'execution provisoire' : "executionProvisoire",
        'interdiction d\'exercer l\'activité professionnelle ayant permis la commission de l\'infraction ' : "interdictionProfession",
        'durée.1' : "dureeInterdictionProfession",
        'interdiction d\'exercer une profession commerciale ou industrielle, de diriger, d\'administrer, de gérer, de controler une entreprise, une société' : "interdictionEntreprise",
        'durée.2' : "dureeInterdictionEntreprise",
        'privation des droits civiques, civiles, de famille' : "privationDroitsCiviques",
        'durée.3' : "dureePrivationDroitsCiviques",
        'privation du droit de vote et d\'éligibilité' : "privationDroitVote",
        'durée.4' : "dureePrivationDroitVote",
        'suspension du permis de conduire' : "suspensionPermisConduire",
        'durée.5' : "dureeSuspensionPermisConduire",
        'privation du droit d\'exercer une fonction juridictionnelle, d\'expert, de representation ou d\'assistance en justice' : "privationFonctionJuridique",
        'durée.6' : "dureePrivationFonctionJuridique",
        'confiscation biens meubles ' : "confiscationBiensMeubles",
        'confiscation biens immeubles ' : "confiscationBiensImmeubles",
        'montant de la confiscation ' : "montantConfiscation",
        'Indemnisation des parties civiles ' : "indemnisationPartiesCiviles",
        'Appel de la décision ' : "appelDecision",
        'durée de la procédure (entre la fin de la durée de prévention et jusqu\'à la décision de première instance)' : "dureeProcedure"
    }

    tableau.rename(columns=customIndex, inplace=True) 
    return